# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.subscriber.user.form:
        class: AppBundle\Subscriber\UserFormSubscriber
        tags:
            - { name: kernel.event_subscriber }

    app.service.order:
            class: AppBundle\Service\OrderService
            arguments: [ "@doctrine", "@session", "@request_stack" ]

    admin.subscriber.kernel.event:
        class: adminBundle\Subscriber\KernelEventsSubscriber
        arguments: [ "@twig", "@session" ]
        tags:
            - { name: kernel.event_subscriber }

    app.subscriber.visit.events:
            class: AppBundle\Subscriber\VisitEventsSubscriber
            tags:
                - { name: kernel.event_subscriber }

    admin.subscriber.category.form:
        class: adminBundle\Subscriber\CategoryFormSubscriber
        tags:
            - { name: kernel.event_subscriber }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    admin.service.utils.string:
        class: adminBundle\Service\Utils\StringService

    admin.service.upload:
        class: adminBundle\Service\UploadService
        arguments: ["@admin.service.utils.string", "%upload_dir%"]

    admin.service.unlink:
        class: adminBundle\Service\UnlinkService
        arguments: [ "%upload_dir%" ]

    admin.listener.product:
        class: adminBundle\Listener\ProductListener
        arguments: ["@admin.service.upload", "@admin.service.unlink"]
        tags:
            - { name: doctrine.orm.entity_listener }
            
    app.listener.user:
        class: AppBundle\Listener\UserListener
        arguments: ["@admin.service.upload", "@admin.service.unlink"]
        tags:
            - { name: doctrine.orm.entity_listener }

    admin.twig.extension:
        class: adminBundle\Twig\AppExtension
        arguments: [ '@doctrine', '@twig' ]
        tags:
            - { name: twig.extension}
