<?php

namespace AppBundle\Command;


use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class UserAddRoleCommand extends ContainerAwareCommand
{

    protected function configure()
    {
        $this
            ->setName('app:user:role:add')
            ->setDescription('Add role to an user')
            ->addArgument('username', InputArgument::REQUIRED, 'Define username')
            ->addArgument('role', InputArgument::REQUIRED, 'Define role')
            ;
        //parent::configure();
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        //appel des arguments en entrée
        $username = $input->getArgument('username');
        $role = $input->getArgument('role');

        //appel de doctrine
        $container = $this->getContainer();
        $doctrine= $container->get('doctrine');
        $em = $doctrine->getManager();

        // Désactivation de l'écouteur de "preUpdate" pour pouvoir utiliser la commande
        $em->getClassMetaData('AppBundle:User')->entityListeners; // récupération des écouteurs (pour les visualiser grâce au dump)
        unset($em->getClassMetaData('AppBundle:User')->entityListeners['preUpdate']); // suppression de l'écouteur qui pose pb
        //dump($em->getClassMetaData('AppBundle:User')->entityListeners); exit;


        $rcUser = $doctrine->getRepository('AppBundle:User')->findOneBy([
            'username' => $username
        ]);

        $rcRole = $doctrine->getRepository('AppBundle:Role')->findOneBy([
            'name' => 'ROLE_' . strtoupper($role)
        ]);

        $rcUser->addRole($rcRole);

        $em->persist($rcUser);
        $em->flush();


        //sortie
        //writeln : avec un saut de ligne à la fin
        $output->writeln("$username // $role");

        //à mettre en commentaire sinon erreur
        //parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}